<?xml version="1.0"?>
<robot name="my_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="common_properties.xacro" />
    <xacro:include filename="mobile_base.xacro" />
    <xacro:include filename="camera.xacro" />
    <xacro:include filename="mobile_base_gazebo.xacro" />
    <xacro:include filename="arm.xacro" />
    <xacro:include filename="arm_gazebo.xacro" />

    <joint name="base_arm_joint" type="fixed">
        <parent link="base_link" />
        <child link="arm_base_link" />
        <origin xyz="${base_length / 3.0} 0 ${base_hight}" rpy="0 0 ${pi / 2.0}" />
    </joint>
</robot>